connection:
  info:
    ip: 127.0.0.1
    port: 5000
    tls_config:
      enable: false
  name: FlaskConnection
  path: ibmfl.connection.flask_connection
  sync: false
data:
  info:
    txt_file: backend/datasets/adult.data
  name: AdultSklearnDataHandler
  path: ibmfl.util.data_handlers.adult_sklearn_data_handler
fusion:
  name: IterAvgFusionHandler
  path: ibmfl.aggregator.fusion.iter_avg_fusion_handler
hyperparams:
  global:
    parties: 2
    round: '2'
    rounds: 3
    termination_accuracy: 0.9
  local:
    training:
      max_iter: 2
protocol_handler:
  name: ProtoHandler
  path: ibmfl.aggregator.protohandler.proto_handler
